# Generated by Django 5.2.7 on 2025-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WgtGdPortalMst',
            fields=[
                ('portal_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('portal_nm', models.CharField(max_length=100)),
                ('portal_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('portal_url', models.CharField(blank=True, max_length=100, null=True)),
                ('portal_logo_img_url', models.CharField(blank=True, max_length=100, null=True)),
                ('portal_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('bound_box_from_data', models.CharField(default='Y', max_length=1)),
                ('max_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('max_long', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('min_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('min_long', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('projection', models.CharField(blank=True, max_length=20, null=True)),
                ('max_zoom', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('map_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('bg_color', models.CharField(blank=True, max_length=7, null=True)),
                ('base_map_typ', models.CharField(default='R', max_length=1)),
                ('base_map_url', models.CharField(blank=True, max_length=100, null=True)),
                ('portal_copyright', models.CharField(blank=True, max_length=100, null=True)),
                ('act_flg', models.CharField(default='A', max_length=1)),
                ('mod_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'wgt_gd_portal_mst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WgtGdPortalUserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_id', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=25)),
                ('privilege_flg', models.CharField(default='V', max_length=1)),
                ('act_flg', models.CharField(default='A', max_length=1)),
                ('mod_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'wgt_gd_portal_user_map',
                'managed': False,
            },
        ),
    ]
