# Generated by Django 5.2.7 on 2025-11-06 12:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WgtGdLayerMst',
            fields=[
                ('layer_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('layer_nm', models.CharField(max_length=50)),
                ('layer_nature', models.CharField(default='V', max_length=1)),
                ('layer_geom_typ', models.CharField(default='P', max_length=1)),
                ('layer_data_src_typ', models.CharField(default='OBJ', max_length=3)),
                ('obj_id', models.CharField(blank=True, max_length=5, null=True)),
                ('obj_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('file_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('wms_url', models.CharField(blank=True, max_length=100, null=True)),
                ('wfs_url', models.CharField(blank=True, max_length=100, null=True)),
                ('web_map_tile_service', models.CharField(blank=True, max_length=100, null=True)),
                ('tile_map_service', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_layer_flg', models.CharField(default='N', max_length=1)),
                ('app_id', models.CharField(blank=True, max_length=8, null=True)),
                ('form_id', models.CharField(blank=True, max_length=8, null=True)),
                ('layer_edit_flg', models.CharField(default='N', max_length=1)),
                ('bound_box_from_data', models.CharField(default='Y', max_length=1)),
                ('max_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('max_long', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('min_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('min_long', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('projection', models.CharField(blank=True, max_length=20, null=True)),
                ('max_zoom', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('act_flg', models.CharField(default='A', max_length=1)),
                ('mod_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'wgt_gd_layer_mst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WgtGdPortalLayerMap',
            fields=[
                ('portal_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('layer_id', models.CharField(max_length=5)),
                ('style_id', models.CharField(max_length=5)),
                ('label_text_col_nm', models.CharField(blank=True, max_length=50, null=True)),
                ('label_view_zoom_level', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('override_style_flg', models.CharField(default='N', max_length=1)),
                ('layer_sld_xml_code', models.CharField(blank=True, max_length=4000, null=True)),
                ('act_flg', models.CharField(default='A', max_length=1)),
                ('mod_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'wgt_gd_portal_layer_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
