# Generated by Django 5.2.7 on 2025-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WgtGdObjMst',
            fields=[
                ('obj_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('obj_nm', models.CharField(max_length=50)),
                ('obj_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('geom_typ', models.CharField(default='N', max_length=1)),
                ('obj_create_typ_flg', models.CharField(default='D', max_length=1)),
                ('act_flg', models.CharField(default='A', max_length=1)),
                ('mod_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'wgt_gd_obj_mst',
                'managed': False,
            },
        ),
    ]
