# Generated by Django 5.2.7 on 2025-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SutAppUserLog',
            fields=[
                ('app_log_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_dt', models.DateTimeField()),
                ('ip_addr', models.CharField(max_length=15)),
                ('user_id', models.CharField(max_length=25)),
                ('sys_dt', models.DateField()),
                ('mod_id', models.CharField(default='M0002', max_length=6)),
                ('logout_flg', models.CharField(default='N', max_length=1)),
                ('login_dt', models.DateTimeField()),
                ('logout_dt', models.DateTimeField(blank=True, null=True)),
                ('mob_no', models.CharField(blank=True, max_length=100, null=True)),
                ('login_lvl_ref_cd', models.CharField(default='000002', max_length=6)),
                ('data_lvl_ref_cd', models.CharField(default='000001', max_length=6)),
                ('log_typ', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'sut_app_user_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SutLoginAttmptLog',
            fields=[
                ('login_attmpt_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mod_id', models.CharField(blank=True, max_length=6, null=True)),
                ('user_id', models.CharField(max_length=25)),
                ('pwd', models.CharField(max_length=100)),
                ('ip_addr', models.CharField(max_length=15)),
                ('sucess_flg', models.CharField(default='N', max_length=1)),
                ('fail_rson', models.CharField(blank=True, max_length=200, null=True)),
                ('app_log_no', models.CharField(blank=True, max_length=20, null=True)),
                ('mod_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sut_login_attmpt_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SutUserLocMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('lvl_ref_cd', models.CharField(max_length=6)),
                ('list_flg', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('add_flg', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('mod_flg', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('del_flg', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('view_flg', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('canc_flg', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('act_flg', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='A', max_length=1)),
                ('mod_dt', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sut_user_loc_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SutUserMst',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('user_nm', models.CharField(max_length=100)),
                ('user_pwd', models.CharField(max_length=100)),
                ('eff_dt', models.DateField()),
                ('exp_dt', models.DateField(blank=True, null=True)),
                ('login_flg', models.CharField(default='1', max_length=1)),
                ('act_flg', models.CharField(default='A', max_length=1)),
                ('mob_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sut_user_mst',
                'managed': False,
            },
        ),
    ]
