# Generated by Django 5.2.7 on 2025-11-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WgtGdGeomStyleMst',
            fields=[
                ('style_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('style_nm', models.CharField(max_length=100)),
                ('geom_typ', models.CharField(default='P', max_length=1)),
                ('marker_img_url', models.CharField(blank=True, max_length=100, null=True)),
                ('marker_fa_icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('marker_color', models.CharField(blank=True, max_length=7, null=True)),
                ('marker_size', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('marker_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('stroke_color', models.CharField(blank=True, max_length=7, null=True)),
                ('fill_color', models.CharField(blank=True, max_length=7, null=True)),
                ('stroke_width', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('stroke_opacity', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('fill_opacity', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('label_font_typ', models.CharField(blank=True, max_length=50, null=True)),
                ('label_font_size', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('label_color', models.CharField(blank=True, max_length=7, null=True)),
                ('label_bg_color', models.CharField(blank=True, max_length=7, null=True)),
                ('label_bg_stroke_width', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('label_offset_xy', models.CharField(blank=True, max_length=20, null=True)),
                ('sld_xml_flg', models.CharField(default='N', max_length=1)),
                ('sld_xml_code', models.CharField(blank=True, max_length=4000, null=True)),
                ('act_flg', models.CharField(default='A', max_length=1)),
                ('mod_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'wgt_gd_geom_style_mst',
                'managed': False,
            },
        ),
    ]
